apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: kustomize-parameters
  namespace: kube-system
  envs:
    - params.env

vars:
- name: environment
  objref:
    kind: ConfigMap
    name: kustomize-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.environment

configurations:
 - params.yaml
